dist: xenial

language: python

python:
  - "3.7"

install:
  - pip install flask
  - pip install flask_restful
  - pip install requests
  - pip install -e .

script:
  - python API_Testing/test_api_handler.py
  - python API_Testing/test_api_wrapper_handler.py