dist: xenial

language: python

python:
  - "3.7"

cache: pip

install:
  - pip install flask
  - pip install flask_restful
  - pip install requests
  - pip install requests_cache
  - pip install coverage
  - pip install -e .

script:
  - coverage run  API_IntegrationTesting/test_wrapper.py
  - coverage run  API_Testing/test_api_handler.py
  - coverage run  API_Testing/test_api_wrapper_handler.py

after_success:
  bash <(curl -s https://codecov.io/bash)
